### ISSUE TITLE
ArraySum: Some suggestions

### ISSUE THREAD

**Issue by shalithasuranga** [heshanWick/internship-4.0#3]
- [x] Use the class as `ArrayAdder`. and use methods `setFirstArray(ar1)`, `setSecondArray(ar2)`, and `getNewArray()`
- [x] Ask user to enter array elements
- [x] Return new array with `getNewArray`
- [x] Use dynamic data structure (Eg: ArrayList)

**Comment by heshanWick** [comment]
Done 👍
